/* This file is generated by lego.py. Do not edit.*/
#include <dsensor.h>
void _ZN7brickOS7brickOS7dsensor15ds_rotation_offEs(short arg0){
  ds_rotation_off((arg0==1?&SENSOR_1:arg0==2?&SENSOR_2:&SENSOR_3));
}
