/* This file is generated by lego.py. Do not edit.*/
#include <dsensor.h>
void _ZN7brickOS7brickOS7dsensor15ds_rotation_setEss(short arg0, int arg1){
  ds_rotation_set((arg0==1?&SENSOR_1:arg0==2?&SENSOR_2:&SENSOR_3), arg1);
}
